---
title: "Vacant Parcels Owned by Public Entities"
---


```{r}
#| include: FALSE
library(sf)
library(tidyverse)
library(leaflet)
library(cpaltemplates)
library(units)

cityVacant <- st_read("data/Public Land in the City of Dallas.geojson")

citySm <- cityVacant %>%
  select(GIS_PARCEL_ID, ACCOUNT_NUM, STREET_NUM, FULL_STREET_NAME, PROPERTY_CITY, PROPERTY_ZIPCODE, OWNERSHIP_GROUP, LAND_VAL, PREV_MKT_VAL, SPTD_CODE) %>%
  mutate(ZIP = str_extract(PROPERTY_ZIPCODE, "^\\d{5}")) %>%
  st_transform(crs = 4326)

ownerGroups <-  citySm[st_is_valid(citySm), ] %>%
  mutate(AreaSqMi = set_units(set_units(st_area(.), "m^2"), "mi^2")) %>%
  st_drop_geometry() %>%
  group_by(OWNERSHIP_GROUP) %>%
  summarize(tot_accounts = n(),
            AreaSqMi = as.numeric(round(sum(AreaSqMi), digits = 4)))

count_total <- scales::comma(nrow(st_drop_geometry(citySm)))

count_cod <- scales::comma(nrow(st_drop_geometry(citySm) %>% filter(OWNERSHIP_GROUP == "CITY OF DALLAS")))
count_dcollege <- scales::comma(nrow(st_drop_geometry(citySm) %>% filter(OWNERSHIP_GROUP == "DALLAS COLLEGE")))
count_dcounty <- scales::comma(nrow(st_drop_geometry(citySm) %>% filter(OWNERSHIP_GROUP == "DALLAS COUNTY")))
count_dha <- scales::comma(nrow(st_drop_geometry(citySm) %>% filter(OWNERSHIP_GROUP == "DALLAS HOUSING AUTHORITY")))
count_disd <- scales::comma(nrow(st_drop_geometry(citySm) %>% filter(OWNERSHIP_GROUP == "DALLAS ISD")))
count_dart <- scales::comma(nrow(st_drop_geometry(citySm) %>% filter(OWNERSHIP_GROUP == "DART")))
count_multiple <- scales::comma(nrow(st_drop_geometry(citySm) %>% filter(OWNERSHIP_GROUP == "MULTIPLE OWNERS")))

dallasBound <- st_read("data/City of Dallas Boundary.geojson") %>%
  st_transform(crs = 4326)

map_palette <- c("#008097", "#ED683F", "#EACA2D", "#5C2B1C", "#ED018C", "#185411")

```

::: column-screen-inset

```{=html}
<div class="mainboxbox">
<div class="mainbox">
```

:::: {.card}

```{=html}
<div class="cardbox">

<div class="left-card-col dark-col">
```

```{=html}
  <div class="card-side" style="width: 94%;">
```

# There are `r count_total` unique vacant lots owned by public entities within the City of Dallas

```{=html}
    <div class="subtext">
      &#8212; Dallas Central Appraisal District (2023)
    </div>
  </div>
</div>
```

```{=html}
<div class="right-card-col">

  <div style="width: 3%">
  </div>

  <div class="card-side">
    
    <h4>
      <div class="rounded-outline"><b>`r count_cod`</b></div> listed as <span style="color: #008097;">City of Dallas</span>
    </h4>
    <h4>
      <div class="rounded-outline"><b>`r count_dcounty`</b></div> listed as <span style="color: #ED683F;">Dallas County</span>
    </h4>
    <h4>
      <div class="rounded-outline"><b>`r count_dart`</b></div> listed as <span style="color: #bd9e0b;">DART</span>
    </h4>
    <h4>
      <div class="rounded-outline"><b>`r count_dcollege`</b></div> listed as <span style="color: #5C2B1C;">Dallas College</span>
    </h4>
    <h4>
      <div class="rounded-outline"><b>`r count_disd`</b></div> listed as <span style="color: #ED018C;">Dallas Independent School District</span>
    </h4>
    <h4>
      <div class="rounded-outline"><b>`r count_dha`</b></div> listed as <span style="color: #ED018C;">Dallas Housing Authority</span>
    </h4>
    <h4>
      <div class="rounded-outline"><b>`r count_multiple`</b></div> listed as owned by a <span style="color: #185411;">Multiple Owners</span>
    </h4>

  </div>
</div>

</div>

```

::::

:::

The map below visualizes the vacant land within the boundaries of the City of Dallas currently owned by public agencies such as the City of Dallas, Dallas County, DART, and Dallas ISD, among others using 2023 DCAD Certified rolls.

```{r}
#| fig-height: 8
popup <- paste0("<b>", "Account Number: ", "</b>", citySm$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", citySm$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", citySm$STREET_NUM, " ", citySm$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", citySm$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", citySm$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(citySm$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(citySm$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", citySm$SPTD_CODE, "<br>"
               )

cityDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "CITY OF DALLAS")

countyDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "DALLAS COUNTY")

isdDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "DALLAS ISD")

multiple <- citySm %>%
  filter(OWNERSHIP_GROUP == "MULTIPLE OWNERS")

haDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "DALLAS HOUSING AUTHORITY")

dart <- citySm %>%
  filter(OWNERSHIP_GROUP == "DART")

collegeDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "DALLAS COLLEGE")

leaflet() %>%
#  setView(lng = -96.7970, lat = 32.7767, zoom = 10) %>%
  addTiles(urlTemplate = cpal_mapbox_color, attribution = cpal_leaflet) %>%
  addPolygons(data = dallasBound,
              fillColor = "#595959",
              color = "#595959",
              weight = 2,
              opacity = 1,
              fillOpacity = 0
              ) %>%
  addPolygons(data = cityDallas,
              fillColor = "#008097",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "City of Dallas",
              popup = ~paste0("<b>", "Account Number: ", "</b>", cityDallas$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", cityDallas$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", cityDallas$STREET_NUM, " ", cityDallas$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", cityDallas$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", cityDallas$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(cityDallas$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(cityDallas$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", cityDallas$SPTD_CODE, "<br>"
               ),
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addPolygons(data = countyDallas,
              fillColor = "#E98816",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Dallas County",
              popup = ~paste0("<b>", "Account Number: ", "</b>", countyDallas$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", countyDallas$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", countyDallas$STREET_NUM, " ", countyDallas$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", countyDallas$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", countyDallas$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(countyDallas$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(countyDallas$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", countyDallas$SPTD_CODE, "<br>"
               ),
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addPolygons(data = isdDallas,
              fillColor = "#EA8B98",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Dallas ISD",
              popup = ~paste0("<b>", "Account Number: ", "</b>", isdDallas$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", isdDallas$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", isdDallas$STREET_NUM, " ", isdDallas$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", isdDallas$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", isdDallas$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(isdDallas$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(isdDallas$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", isdDallas$SPTD_CODE, "<br>"
               ),
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addPolygons(data = multiple,
              fillColor = "#EACA2D",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Multiple Owners",
              popup = ~paste0("<b>", "Account Number: ", "</b>", multiple$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", multiple$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", multiple$STREET_NUM, " ", multiple$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", multiple$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", multiple$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(multiple$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(multiple$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", multiple$SPTD_CODE, "<br>"
               ),
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addPolygons(data = haDallas,
              fillColor = "#851E2C",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Dallas Housing Authority",
              popup = ~paste0("<b>", "Account Number: ", "</b>", haDallas$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", haDallas$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", haDallas$STREET_NUM, " ", haDallas$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", haDallas$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", haDallas$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(haDallas$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(haDallas$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", haDallas$SPTD_CODE, "<br>"
               ),
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
    addPolygons(data = dart,
              fillColor = "#1E4A4A",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "DART",
              popup = ~paste0("<b>", "Account Number: ", "</b>", dart$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", dart$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", dart$STREET_NUM, " ", dart$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", dart$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", dart$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(dart$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(dart$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", dart$SPTD_CODE, "<br>"
               ),
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
    addPolygons(data = collegeDallas,
              fillColor = "#F7314C",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Dallas College",
              popup = ~paste0("<b>", "Account Number: ", "</b>", collegeDallas$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", collegeDallas$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", collegeDallas$STREET_NUM, " ", collegeDallas$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", collegeDallas$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", collegeDallas$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(collegeDallas$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(collegeDallas$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", collegeDallas$SPTD_CODE, "<br>"
               ),
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addLayersControl(
    overlayGroups = c("City of Dallas",
                      "Dallas County",
                      "Dallas ISD",
                      "DART",
                      "Dallas Housing Authority",
                       
                      "Dallas College",
                      "Multiple Owners"),
    position = "topright",
    options = layersControlOptions(collapsed = FALSE))
```